# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:
  build:
    docker:
      - image: node:9.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-npm-dependencies-{{ checksum "client/yarn.lock" }}

      - run:
          name: install dependencies
          command: |
            cd client && yarn install

      - save_cache:
          paths:
            - ./client/node_modules
          key: v1-npm-dependencies-{{ checksum "client/yarn.lock" }}

      - run:
          name: run tests
          command: |
            cd client && yarn test
            ./node_modules/eslint/bin/eslint.js . --quiet

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - build
